// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Event struct {
	ID        *string `json:"id"`
	Name      *string `json:"name"`
	IsPrivate *string `json:"isPrivate"`
	Email     *string `json:"email"`
}

type User struct {
	ID         *string `json:"id"`
	Name       *string `json:"name"`
	IsVerified *string `json:"isVerified"`
	Email      *string `json:"email"`
}
